//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPrice", ReplyAction="*")]
        Client.ServiceReference1.addPriceResponse addPrice(Client.ServiceReference1.addPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.addPriceResponse> addPriceAsync(Client.ServiceReference1.addPriceRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletePrice", ReplyAction="*")]
        Client.ServiceReference1.deletePriceResponse deletePrice(Client.ServiceReference1.deletePriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.deletePriceResponse> deletePriceAsync(Client.ServiceReference1.deletePriceRequest request);
        
        // CODEGEN: Generating message contract since element name currentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePrice", ReplyAction="*")]
        Client.ServiceReference1.updatePriceResponse updatePrice(Client.ServiceReference1.updatePriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.updatePriceResponse> updatePriceAsync(Client.ServiceReference1.updatePriceRequest request);
        
        // CODEGEN: Generating message contract since element name getDataPriceResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataPrice", ReplyAction="*")]
        Client.ServiceReference1.getDataPriceResponse getDataPrice(Client.ServiceReference1.getDataPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataPriceResponse> getDataPriceAsync(Client.ServiceReference1.getDataPriceRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPatient", ReplyAction="*")]
        Client.ServiceReference1.addPatientResponse addPatient(Client.ServiceReference1.addPatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPatient", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.addPatientResponse> addPatientAsync(Client.ServiceReference1.addPatientRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePatient", ReplyAction="*")]
        Client.ServiceReference1.updatePatientResponse updatePatient(Client.ServiceReference1.updatePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePatient", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.updatePatientResponse> updatePatientAsync(Client.ServiceReference1.updatePatientRequest request);
        
        // CODEGEN: Generating message contract since element name getDataPatientResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataPatient", ReplyAction="*")]
        Client.ServiceReference1.getDataPatientResponse getDataPatient(Client.ServiceReference1.getDataPatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataPatient", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataPatientResponse> getDataPatientAsync(Client.ServiceReference1.getDataPatientRequest request);
        
        // CODEGEN: Generating message contract since element name treatment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addProgramme", ReplyAction="*")]
        Client.ServiceReference1.addProgrammeResponse addProgramme(Client.ServiceReference1.addProgrammeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addProgramme", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.addProgrammeResponse> addProgrammeAsync(Client.ServiceReference1.addProgrammeRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProgramme", ReplyAction="*")]
        Client.ServiceReference1.deleteProgrammeResponse deleteProgramme(Client.ServiceReference1.deleteProgrammeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProgramme", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.deleteProgrammeResponse> deleteProgrammeAsync(Client.ServiceReference1.deleteProgrammeRequest request);
        
        // CODEGEN: Generating message contract since element name getDataProgrammeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataProgramme", ReplyAction="*")]
        Client.ServiceReference1.getDataProgrammeResponse getDataProgramme(Client.ServiceReference1.getDataProgrammeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDataProgramme", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataProgrammeResponse> getDataProgrammeAsync(Client.ServiceReference1.getDataProgrammeRequest request);
        
        // CODEGEN: Generating message contract since element name getNameProgrammeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNameProgramme", ReplyAction="*")]
        Client.ServiceReference1.getNameProgrammeResponse getNameProgramme(Client.ServiceReference1.getNameProgrammeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNameProgramme", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getNameProgrammeResponse> getNameProgrammeAsync(Client.ServiceReference1.getNameProgrammeRequest request);
        
        // CODEGEN: Generating message contract since element name getPriceProgrammeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPriceProgramme", ReplyAction="*")]
        Client.ServiceReference1.getPriceProgrammeResponse getPriceProgramme(Client.ServiceReference1.getPriceProgrammeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPriceProgramme", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.getPriceProgrammeResponse> getPriceProgrammeAsync(Client.ServiceReference1.getPriceProgrammeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPrice", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addPriceRequestBody Body;
        
        public addPriceRequest() {
        }
        
        public addPriceRequest(Client.ServiceReference1.addPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double price;
        
        public addPriceRequestBody() {
        }
        
        public addPriceRequestBody(string name, string type, double price) {
            this.name = name;
            this.type = type;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addPriceResponseBody Body;
        
        public addPriceResponse() {
        }
        
        public addPriceResponse(Client.ServiceReference1.addPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addPriceResponseBody {
        
        public addPriceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePrice", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.deletePriceRequestBody Body;
        
        public deletePriceRequest() {
        }
        
        public deletePriceRequest(Client.ServiceReference1.deletePriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deletePriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public deletePriceRequestBody() {
        }
        
        public deletePriceRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.deletePriceResponseBody Body;
        
        public deletePriceResponse() {
        }
        
        public deletePriceResponse(Client.ServiceReference1.deletePriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deletePriceResponseBody {
        
        public deletePriceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePrice", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.updatePriceRequestBody Body;
        
        public updatePriceRequest() {
        }
        
        public updatePriceRequest(Client.ServiceReference1.updatePriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updatePriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double price;
        
        public updatePriceRequestBody() {
        }
        
        public updatePriceRequestBody(string currentName, string name, string type, double price) {
            this.currentName = currentName;
            this.name = name;
            this.type = type;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.updatePriceResponseBody Body;
        
        public updatePriceResponse() {
        }
        
        public updatePriceResponse(Client.ServiceReference1.updatePriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updatePriceResponseBody {
        
        public updatePriceResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataPrice", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataPriceRequestBody Body;
        
        public getDataPriceRequest() {
        }
        
        public getDataPriceRequest(Client.ServiceReference1.getDataPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDataPriceRequestBody {
        
        public getDataPriceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataPriceResponseBody Body;
        
        public getDataPriceResponse() {
        }
        
        public getDataPriceResponse(Client.ServiceReference1.getDataPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString getDataPriceResult;
        
        public getDataPriceResponseBody() {
        }
        
        public getDataPriceResponseBody(Client.ServiceReference1.ArrayOfString getDataPriceResult) {
            this.getDataPriceResult = getDataPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPatient", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addPatientRequestBody Body;
        
        public addPatientRequest() {
        }
        
        public addPatientRequest(Client.ServiceReference1.addPatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        public addPatientRequestBody() {
        }
        
        public addPatientRequestBody(string name, string firstName, string phoneNumber) {
            this.name = name;
            this.firstName = firstName;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addPatientResponseBody Body;
        
        public addPatientResponse() {
        }
        
        public addPatientResponse(Client.ServiceReference1.addPatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addPatientResponseBody {
        
        public addPatientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePatient", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.updatePatientRequestBody Body;
        
        public updatePatientRequest() {
        }
        
        public updatePatientRequest(Client.ServiceReference1.updatePatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updatePatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phoneNumber;
        
        public updatePatientRequestBody() {
        }
        
        public updatePatientRequestBody(int index, string name, string firstName, string phoneNumber) {
            this.index = index;
            this.name = name;
            this.firstName = firstName;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.updatePatientResponseBody Body;
        
        public updatePatientResponse() {
        }
        
        public updatePatientResponse(Client.ServiceReference1.updatePatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updatePatientResponseBody {
        
        public updatePatientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataPatient", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataPatientRequestBody Body;
        
        public getDataPatientRequest() {
        }
        
        public getDataPatientRequest(Client.ServiceReference1.getDataPatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDataPatientRequestBody {
        
        public getDataPatientRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataPatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataPatientResponseBody Body;
        
        public getDataPatientResponse() {
        }
        
        public getDataPatientResponse(Client.ServiceReference1.getDataPatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataPatientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString getDataPatientResult;
        
        public getDataPatientResponseBody() {
        }
        
        public getDataPatientResponseBody(Client.ServiceReference1.ArrayOfString getDataPatientResult) {
            this.getDataPatientResult = getDataPatientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addProgrammeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addProgramme", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addProgrammeRequestBody Body;
        
        public addProgrammeRequest() {
        }
        
        public addProgrammeRequest(Client.ServiceReference1.addProgrammeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addProgrammeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string treatment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime time;
        
        public addProgrammeRequestBody() {
        }
        
        public addProgrammeRequestBody(string treatment, string name, string firstName, System.DateTime time) {
            this.treatment = treatment;
            this.name = name;
            this.firstName = firstName;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addProgrammeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addProgrammeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.addProgrammeResponseBody Body;
        
        public addProgrammeResponse() {
        }
        
        public addProgrammeResponse(Client.ServiceReference1.addProgrammeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addProgrammeResponseBody {
        
        public addProgrammeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteProgrammeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteProgramme", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.deleteProgrammeRequestBody Body;
        
        public deleteProgrammeRequest() {
        }
        
        public deleteProgrammeRequest(Client.ServiceReference1.deleteProgrammeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteProgrammeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        public deleteProgrammeRequestBody() {
        }
        
        public deleteProgrammeRequestBody(string name, string firstName) {
            this.name = name;
            this.firstName = firstName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteProgrammeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteProgrammeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.deleteProgrammeResponseBody Body;
        
        public deleteProgrammeResponse() {
        }
        
        public deleteProgrammeResponse(Client.ServiceReference1.deleteProgrammeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteProgrammeResponseBody {
        
        public deleteProgrammeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataProgrammeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataProgramme", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataProgrammeRequestBody Body;
        
        public getDataProgrammeRequest() {
        }
        
        public getDataProgrammeRequest(Client.ServiceReference1.getDataProgrammeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDataProgrammeRequestBody {
        
        public getDataProgrammeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataProgrammeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataProgrammeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getDataProgrammeResponseBody Body;
        
        public getDataProgrammeResponse() {
        }
        
        public getDataProgrammeResponse(Client.ServiceReference1.getDataProgrammeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDataProgrammeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString getDataProgrammeResult;
        
        public getDataProgrammeResponseBody() {
        }
        
        public getDataProgrammeResponseBody(Client.ServiceReference1.ArrayOfString getDataProgrammeResult) {
            this.getDataProgrammeResult = getDataProgrammeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNameProgrammeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNameProgramme", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getNameProgrammeRequestBody Body;
        
        public getNameProgrammeRequest() {
        }
        
        public getNameProgrammeRequest(Client.ServiceReference1.getNameProgrammeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getNameProgrammeRequestBody {
        
        public getNameProgrammeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNameProgrammeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNameProgrammeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getNameProgrammeResponseBody Body;
        
        public getNameProgrammeResponse() {
        }
        
        public getNameProgrammeResponse(Client.ServiceReference1.getNameProgrammeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNameProgrammeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString getNameProgrammeResult;
        
        public getNameProgrammeResponseBody() {
        }
        
        public getNameProgrammeResponseBody(Client.ServiceReference1.ArrayOfString getNameProgrammeResult) {
            this.getNameProgrammeResult = getNameProgrammeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPriceProgrammeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPriceProgramme", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getPriceProgrammeRequestBody Body;
        
        public getPriceProgrammeRequest() {
        }
        
        public getPriceProgrammeRequest(Client.ServiceReference1.getPriceProgrammeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPriceProgrammeRequestBody {
        
        public getPriceProgrammeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPriceProgrammeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPriceProgrammeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.getPriceProgrammeResponseBody Body;
        
        public getPriceProgrammeResponse() {
        }
        
        public getPriceProgrammeResponse(Client.ServiceReference1.getPriceProgrammeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPriceProgrammeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString getPriceProgrammeResult;
        
        public getPriceProgrammeResponseBody() {
        }
        
        public getPriceProgrammeResponseBody(Client.ServiceReference1.ArrayOfString getPriceProgrammeResult) {
            this.getPriceProgrammeResult = getPriceProgrammeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Client.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebServiceSoap>, Client.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.addPriceResponse Client.ServiceReference1.WebServiceSoap.addPrice(Client.ServiceReference1.addPriceRequest request) {
            return base.Channel.addPrice(request);
        }
        
        public void addPrice(string name, string type, double price) {
            Client.ServiceReference1.addPriceRequest inValue = new Client.ServiceReference1.addPriceRequest();
            inValue.Body = new Client.ServiceReference1.addPriceRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.price = price;
            Client.ServiceReference1.addPriceResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).addPrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.addPriceResponse> Client.ServiceReference1.WebServiceSoap.addPriceAsync(Client.ServiceReference1.addPriceRequest request) {
            return base.Channel.addPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.addPriceResponse> addPriceAsync(string name, string type, double price) {
            Client.ServiceReference1.addPriceRequest inValue = new Client.ServiceReference1.addPriceRequest();
            inValue.Body = new Client.ServiceReference1.addPriceRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.price = price;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).addPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.deletePriceResponse Client.ServiceReference1.WebServiceSoap.deletePrice(Client.ServiceReference1.deletePriceRequest request) {
            return base.Channel.deletePrice(request);
        }
        
        public void deletePrice(string name) {
            Client.ServiceReference1.deletePriceRequest inValue = new Client.ServiceReference1.deletePriceRequest();
            inValue.Body = new Client.ServiceReference1.deletePriceRequestBody();
            inValue.Body.name = name;
            Client.ServiceReference1.deletePriceResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).deletePrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.deletePriceResponse> Client.ServiceReference1.WebServiceSoap.deletePriceAsync(Client.ServiceReference1.deletePriceRequest request) {
            return base.Channel.deletePriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.deletePriceResponse> deletePriceAsync(string name) {
            Client.ServiceReference1.deletePriceRequest inValue = new Client.ServiceReference1.deletePriceRequest();
            inValue.Body = new Client.ServiceReference1.deletePriceRequestBody();
            inValue.Body.name = name;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).deletePriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.updatePriceResponse Client.ServiceReference1.WebServiceSoap.updatePrice(Client.ServiceReference1.updatePriceRequest request) {
            return base.Channel.updatePrice(request);
        }
        
        public void updatePrice(string currentName, string name, string type, double price) {
            Client.ServiceReference1.updatePriceRequest inValue = new Client.ServiceReference1.updatePriceRequest();
            inValue.Body = new Client.ServiceReference1.updatePriceRequestBody();
            inValue.Body.currentName = currentName;
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.price = price;
            Client.ServiceReference1.updatePriceResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).updatePrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.updatePriceResponse> Client.ServiceReference1.WebServiceSoap.updatePriceAsync(Client.ServiceReference1.updatePriceRequest request) {
            return base.Channel.updatePriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.updatePriceResponse> updatePriceAsync(string currentName, string name, string type, double price) {
            Client.ServiceReference1.updatePriceRequest inValue = new Client.ServiceReference1.updatePriceRequest();
            inValue.Body = new Client.ServiceReference1.updatePriceRequestBody();
            inValue.Body.currentName = currentName;
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.price = price;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).updatePriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getDataPriceResponse Client.ServiceReference1.WebServiceSoap.getDataPrice(Client.ServiceReference1.getDataPriceRequest request) {
            return base.Channel.getDataPrice(request);
        }
        
        public Client.ServiceReference1.ArrayOfString getDataPrice() {
            Client.ServiceReference1.getDataPriceRequest inValue = new Client.ServiceReference1.getDataPriceRequest();
            inValue.Body = new Client.ServiceReference1.getDataPriceRequestBody();
            Client.ServiceReference1.getDataPriceResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).getDataPrice(inValue);
            return retVal.Body.getDataPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataPriceResponse> Client.ServiceReference1.WebServiceSoap.getDataPriceAsync(Client.ServiceReference1.getDataPriceRequest request) {
            return base.Channel.getDataPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getDataPriceResponse> getDataPriceAsync() {
            Client.ServiceReference1.getDataPriceRequest inValue = new Client.ServiceReference1.getDataPriceRequest();
            inValue.Body = new Client.ServiceReference1.getDataPriceRequestBody();
            return ((Client.ServiceReference1.WebServiceSoap)(this)).getDataPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.addPatientResponse Client.ServiceReference1.WebServiceSoap.addPatient(Client.ServiceReference1.addPatientRequest request) {
            return base.Channel.addPatient(request);
        }
        
        public void addPatient(string name, string firstName, string phoneNumber) {
            Client.ServiceReference1.addPatientRequest inValue = new Client.ServiceReference1.addPatientRequest();
            inValue.Body = new Client.ServiceReference1.addPatientRequestBody();
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.phoneNumber = phoneNumber;
            Client.ServiceReference1.addPatientResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).addPatient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.addPatientResponse> Client.ServiceReference1.WebServiceSoap.addPatientAsync(Client.ServiceReference1.addPatientRequest request) {
            return base.Channel.addPatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.addPatientResponse> addPatientAsync(string name, string firstName, string phoneNumber) {
            Client.ServiceReference1.addPatientRequest inValue = new Client.ServiceReference1.addPatientRequest();
            inValue.Body = new Client.ServiceReference1.addPatientRequestBody();
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.phoneNumber = phoneNumber;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).addPatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.updatePatientResponse Client.ServiceReference1.WebServiceSoap.updatePatient(Client.ServiceReference1.updatePatientRequest request) {
            return base.Channel.updatePatient(request);
        }
        
        public void updatePatient(int index, string name, string firstName, string phoneNumber) {
            Client.ServiceReference1.updatePatientRequest inValue = new Client.ServiceReference1.updatePatientRequest();
            inValue.Body = new Client.ServiceReference1.updatePatientRequestBody();
            inValue.Body.index = index;
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.phoneNumber = phoneNumber;
            Client.ServiceReference1.updatePatientResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).updatePatient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.updatePatientResponse> Client.ServiceReference1.WebServiceSoap.updatePatientAsync(Client.ServiceReference1.updatePatientRequest request) {
            return base.Channel.updatePatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.updatePatientResponse> updatePatientAsync(int index, string name, string firstName, string phoneNumber) {
            Client.ServiceReference1.updatePatientRequest inValue = new Client.ServiceReference1.updatePatientRequest();
            inValue.Body = new Client.ServiceReference1.updatePatientRequestBody();
            inValue.Body.index = index;
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.phoneNumber = phoneNumber;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).updatePatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getDataPatientResponse Client.ServiceReference1.WebServiceSoap.getDataPatient(Client.ServiceReference1.getDataPatientRequest request) {
            return base.Channel.getDataPatient(request);
        }
        
        public Client.ServiceReference1.ArrayOfString getDataPatient() {
            Client.ServiceReference1.getDataPatientRequest inValue = new Client.ServiceReference1.getDataPatientRequest();
            inValue.Body = new Client.ServiceReference1.getDataPatientRequestBody();
            Client.ServiceReference1.getDataPatientResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).getDataPatient(inValue);
            return retVal.Body.getDataPatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataPatientResponse> Client.ServiceReference1.WebServiceSoap.getDataPatientAsync(Client.ServiceReference1.getDataPatientRequest request) {
            return base.Channel.getDataPatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getDataPatientResponse> getDataPatientAsync() {
            Client.ServiceReference1.getDataPatientRequest inValue = new Client.ServiceReference1.getDataPatientRequest();
            inValue.Body = new Client.ServiceReference1.getDataPatientRequestBody();
            return ((Client.ServiceReference1.WebServiceSoap)(this)).getDataPatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.addProgrammeResponse Client.ServiceReference1.WebServiceSoap.addProgramme(Client.ServiceReference1.addProgrammeRequest request) {
            return base.Channel.addProgramme(request);
        }
        
        public void addProgramme(string treatment, string name, string firstName, System.DateTime time) {
            Client.ServiceReference1.addProgrammeRequest inValue = new Client.ServiceReference1.addProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.addProgrammeRequestBody();
            inValue.Body.treatment = treatment;
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.time = time;
            Client.ServiceReference1.addProgrammeResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).addProgramme(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.addProgrammeResponse> Client.ServiceReference1.WebServiceSoap.addProgrammeAsync(Client.ServiceReference1.addProgrammeRequest request) {
            return base.Channel.addProgrammeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.addProgrammeResponse> addProgrammeAsync(string treatment, string name, string firstName, System.DateTime time) {
            Client.ServiceReference1.addProgrammeRequest inValue = new Client.ServiceReference1.addProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.addProgrammeRequestBody();
            inValue.Body.treatment = treatment;
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            inValue.Body.time = time;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).addProgrammeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.deleteProgrammeResponse Client.ServiceReference1.WebServiceSoap.deleteProgramme(Client.ServiceReference1.deleteProgrammeRequest request) {
            return base.Channel.deleteProgramme(request);
        }
        
        public void deleteProgramme(string name, string firstName) {
            Client.ServiceReference1.deleteProgrammeRequest inValue = new Client.ServiceReference1.deleteProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.deleteProgrammeRequestBody();
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            Client.ServiceReference1.deleteProgrammeResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).deleteProgramme(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.deleteProgrammeResponse> Client.ServiceReference1.WebServiceSoap.deleteProgrammeAsync(Client.ServiceReference1.deleteProgrammeRequest request) {
            return base.Channel.deleteProgrammeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.deleteProgrammeResponse> deleteProgrammeAsync(string name, string firstName) {
            Client.ServiceReference1.deleteProgrammeRequest inValue = new Client.ServiceReference1.deleteProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.deleteProgrammeRequestBody();
            inValue.Body.name = name;
            inValue.Body.firstName = firstName;
            return ((Client.ServiceReference1.WebServiceSoap)(this)).deleteProgrammeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getDataProgrammeResponse Client.ServiceReference1.WebServiceSoap.getDataProgramme(Client.ServiceReference1.getDataProgrammeRequest request) {
            return base.Channel.getDataProgramme(request);
        }
        
        public Client.ServiceReference1.ArrayOfString getDataProgramme() {
            Client.ServiceReference1.getDataProgrammeRequest inValue = new Client.ServiceReference1.getDataProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getDataProgrammeRequestBody();
            Client.ServiceReference1.getDataProgrammeResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).getDataProgramme(inValue);
            return retVal.Body.getDataProgrammeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getDataProgrammeResponse> Client.ServiceReference1.WebServiceSoap.getDataProgrammeAsync(Client.ServiceReference1.getDataProgrammeRequest request) {
            return base.Channel.getDataProgrammeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getDataProgrammeResponse> getDataProgrammeAsync() {
            Client.ServiceReference1.getDataProgrammeRequest inValue = new Client.ServiceReference1.getDataProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getDataProgrammeRequestBody();
            return ((Client.ServiceReference1.WebServiceSoap)(this)).getDataProgrammeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getNameProgrammeResponse Client.ServiceReference1.WebServiceSoap.getNameProgramme(Client.ServiceReference1.getNameProgrammeRequest request) {
            return base.Channel.getNameProgramme(request);
        }
        
        public Client.ServiceReference1.ArrayOfString getNameProgramme() {
            Client.ServiceReference1.getNameProgrammeRequest inValue = new Client.ServiceReference1.getNameProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getNameProgrammeRequestBody();
            Client.ServiceReference1.getNameProgrammeResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).getNameProgramme(inValue);
            return retVal.Body.getNameProgrammeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getNameProgrammeResponse> Client.ServiceReference1.WebServiceSoap.getNameProgrammeAsync(Client.ServiceReference1.getNameProgrammeRequest request) {
            return base.Channel.getNameProgrammeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getNameProgrammeResponse> getNameProgrammeAsync() {
            Client.ServiceReference1.getNameProgrammeRequest inValue = new Client.ServiceReference1.getNameProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getNameProgrammeRequestBody();
            return ((Client.ServiceReference1.WebServiceSoap)(this)).getNameProgrammeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.getPriceProgrammeResponse Client.ServiceReference1.WebServiceSoap.getPriceProgramme(Client.ServiceReference1.getPriceProgrammeRequest request) {
            return base.Channel.getPriceProgramme(request);
        }
        
        public Client.ServiceReference1.ArrayOfString getPriceProgramme() {
            Client.ServiceReference1.getPriceProgrammeRequest inValue = new Client.ServiceReference1.getPriceProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getPriceProgrammeRequestBody();
            Client.ServiceReference1.getPriceProgrammeResponse retVal = ((Client.ServiceReference1.WebServiceSoap)(this)).getPriceProgramme(inValue);
            return retVal.Body.getPriceProgrammeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.getPriceProgrammeResponse> Client.ServiceReference1.WebServiceSoap.getPriceProgrammeAsync(Client.ServiceReference1.getPriceProgrammeRequest request) {
            return base.Channel.getPriceProgrammeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.getPriceProgrammeResponse> getPriceProgrammeAsync() {
            Client.ServiceReference1.getPriceProgrammeRequest inValue = new Client.ServiceReference1.getPriceProgrammeRequest();
            inValue.Body = new Client.ServiceReference1.getPriceProgrammeRequestBody();
            return ((Client.ServiceReference1.WebServiceSoap)(this)).getPriceProgrammeAsync(inValue);
        }
    }
}
